name: LLMESA
channels:
  - defaults
dependencies:
  - python=3.12
  - pip=24.0
  - pip:
    - llama-index==0.10.36
    - llama-index-llms-ollama==0.1.4
    - llama-index-embeddings-ollama==0.1.3
    - llama-index-embeddings-huggingface==0.1.4
    - ipython
